version: "3.9"
services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@db:5432/ecommerce
      GROQ_API_KEY: your_groq_api_key
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      REACT_APP_API_URL: http://backend:8000/api
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
